### ISSUE TITLE
Doesn't run on Mac

### ISSUE THREAD

**Issue by jamesgpearce** [vlcn-io/vite-starter#14]
Ouch:

```
  VITE v4.4.9  ready in 233 ms

  ➜  Local:   http://localhost:5174/
  ➜  Network: use --host to expose
  ➜  press h to show help
error when starting dev server:
Error: setRawMode EIO
    at ReadStream.setRawMode (node:tty:77:31)
    at bindShortcuts (file:///Users/james/Downloads/vite-starter-main/node_modules/vite/dist/node/chunks/dep-df561101.js:57260:19)
    at CAC.<anonymous> (file:///Users/james/Downloads/vite-starter-main/node_modules/vite/dist/node/cli.js:764:9)
```

Googling for the error makes me think it's something to do with the recent change to get it running on Windows. 

Edit; adding versions:

npm -v => 9.6.7
node -v => v20.3.1

**Comment by tantaman** [comment]
Working for me w/ npm 8.19.2 and node 19.0.1

Upgrading to see what happens.

**Comment by tantaman** [comment]
Also working for me w/ node 20.5.1 and npm 9.8.0

```shell
npm create @vlcn.io@latest my-app
/Users/tantaman/.degit/github/vlcn-io/vite-starter/c1baf0c30519cd3a1bc294a7271665f1f1c23963.tar.gz already exists locally
extracting /Users/tantaman/.degit/github/vlcn-io/vite-starter/c1baf0c30519cd3a1bc294a7271665f1f1c23963.tar.gz to my-app
cloned vlcn-io/vite-starter#HEAD to my-app

🎉 Your project has been successfully created! 🎉

Next steps:
  - cd my-app
  - npm install
  - npm run dev

cd my-app/
npm install
npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

added 575 packages, and audited 576 packages in 37s

112 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm run dev

> my-app@0.0.0 dev
> node ./slurp.mjs && node ./server.js --dev

src/schemas/main.mjs
Pat: dbs/*
Server listening at http://localhost:8080

  VITE v4.4.9  ready in 271 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
Sourcemap for "/Users/tantaman/workspace/my-app/node_modules/@vlcn.io/rx-tbl/dist/index.js" points to missing source files
Sourcemap for "/Users/tantaman/workspace/my-app/node_modules/@vlcn.io/rx-tbl/dist/tblrx.js" points to missing source files
Sourcemap for "/Users/tantaman/workspace/my-app/node_modules/@vlcn.io/xplat-api/dist/xplat-api.js" points to missing source files
Start outbound stream
Start outbound stream
Close outbound stream
vite exited with code 1
```

**Comment by tantaman** [comment]
any more logs for your error?

**Comment by jamesgpearce** [comment]
Let me poke around

**Comment by jamesgpearce** [comment]
OK, I upgraded and also works for me on node 20.5.1 and npm 9.8.0, no other changes :/ - maybe a bad node release in there somewhere?
